### PR TITLE
Fix Translation Issues

### LINKED ISSUE #329: Fix Translation Issue - WordPress.org
There are some issues with the translation on WordPress.org -  
https://translate.wordpress.org/projects/wp-plugins/godam/

### PR DESCRIPTION
**Pull request by subodhr258**
Resolves #329 

Description
1. Strings are made Translation Ready
2. `.pot` file is newly generated
## Screen Recording

https://github.com/user-attachments/assets/bc6da95e-f594-4f34-95a3-3c922155e871

### CODE REVIEW

**Review by mi5t4n — CHANGES_REQUESTED** [review]
I have a few suggestions:
1. Add a composer script to generate pot file and include `wp-cli/i18n-command` as composer dev dependency. Reference: https://github.com/rtCamp/login-with-google/blob/develop/composer.json
2. JS Strings are still not being translated
[Kazam_screencast_00002.webm](https://github.com/user-attachments/assets/3758dd32-ffe9-4a65-badf-ce700b19301f)

File: inc/classes/class-pages.php [hunk 1]
```diff
@@ -381,7 +383,12 @@ public function admin_enqueue_scripts() {
 				);
 			}
 
+			$returned = wp_set_script_translations( 'transcoder-page-script-godam', 'godam', RTGODAM_PATH . 'languages' );
+
 			wp_enqueue_script( 'transcoder-page-script-godam' );
+
+			error_log( 'Translation returned: ' . $returned );
```
Comment (rtBot) [inline inc/classes/class-pages.php:390]: :no_entry_sign: **Error**: error_log() found. Debug code should not normally be used in production (*WordPress.PHP.DevelopmentFunctions.error_log_error_log*).

File: languages/godam-hi_IN.l10n.php [hunk 2]
```diff
@@ -0,0 +1,2 @@
+<?php
```
Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:1]: :no_entry_sign: **Error**: Filenames should be all lowercase with hyphens as word separators. Expected vipgoci-phpcs-scan-tjkzoy.php, but found vipgoci-phpcs-scan-TjKZOY.php (*WordPress.Files.FileName.NotHyphenatedLowercase*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:1]: :no_entry_sign: **Error**: Missing file doc comment (*Squiz.Commenting.FileComment.Missing*).

File: languages/godam-hi_IN.l10n.php [hunk 3]
```diff
@@ -0,0 +1,2 @@
...
+return ['project-id-version'=>'GoDAM 1.0.4','report-msgid-bugs-to'=>'https://wordpress.org/support/plugin/godam','last-translator'=>'','language-team'=>'हिन्दी','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','pot-creation-date'=>'2025-05-09T11:47:22+00:00','po-revision-date'=>'2025-05-09 11:55+0000','x-generator'=>'Loco https://localise.biz/','x-domain'=>'godam','language'=>'hi_IN','plural-forms'=>'nplurals=2; plural=n != 1;','x-loco-version'=>'2.7.2; wp-6.8.1','messages'=>['General Settings'=>'general hindi']];
```
Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space after the array opener in a single line array. Found: no spaces (*NormalizedArrays.Arrays.ArrayBraceSpacing.SpaceAfterArrayOpenerSingleLine*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Short array syntax is not allowed (*Universal.Arrays.DisallowShortArraySyntax.Found*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space before &quot;=&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space after &quot;=&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;report-msgid-bugs-to&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;last-translator&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;language-team&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

**Review by rtBot — CHANGES_REQUESTED** [review]
# Code analysis identified issues
[action-phpcs-code-review](https://github.com/rtCamp/action-phpcs-code-review/) has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 23 errors 


***


Powered by rtCamp's [GitHub Actions Library](https://github.com/rtCamp/github-actions-library)



Posting will continue in further review(s)

File: languages/godam-hi_IN.l10n.php (hunk 3 above)
Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;mime-version&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;content-type&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;content-transfer-encoding&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;pot-creation-date&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;po-revision-date&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;x-generator&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;x-domain&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;language&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;plural-forms&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;x-loco-version&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

**Review by rtBot — CHANGES_REQUESTED** [review]
Previous scan continued.

File: languages/godam-hi_IN.l10n.php (hunk 3 above)
Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space between the comma and &quot;&#039;messages&#039;&quot;. Found: no spaces (*Universal.WhiteSpace.CommaSpacing.NoSpaceAfter*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: Expected 1 space before the array closer in a single line array. Found: no spaces (*NormalizedArrays.Arrays.ArrayBraceSpacing.SpaceBeforeArrayCloserSingleLine*).

Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:2]: :no_entry_sign: **Error**: When a multi-item array uses associative keys, each value should start on a new line (*WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound*).

**Review by rtBot — CHANGES_REQUESTED** [review]
Previous scan continued.

File: godam.php [hunk 4]
```diff
@@ -130,3 +130,14 @@ function rtgodam_plugin_deactivate() {
 }
 
 register_deactivation_hook( __FILE__, 'rtgodam_plugin_deactivate' );
+
+add_action('init', 'load_godam_textdomain');
```
Comment (rtBot) [inline godam.php:134]: :no_entry_sign: **Error**: Expected 1 spaces after opening parenthesis; 0 found (*PEAR.Functions.FunctionCallSignature.SpaceAfterOpenBracket*).

Comment (rtBot) [inline godam.php:134]: :no_entry_sign: **Error**: Expected 1 spaces before closing parenthesis; 0 found (*PEAR.Functions.FunctionCallSignature.SpaceBeforeCloseBracket*).

File: godam.php [hunk 5]
```diff
@@ -130,3 +130,14 @@ function rtgodam_plugin_deactivate() {
...
+
+/**
+ * Load Text Domain
+ *
+ * @return void
+ */
+function load_godam_textdomain() {
+	load_plugin_textdomain( 'godam' );
+}
```
Comment (rtBot) [inline godam.php:143]: :no_entry_sign: **Error**: Expected 1 newline at end of file; 0 found (*PSR2.Files.EndFileNewline.NoneFound*).

File: languages/godam-hi_IN.l10n.php (hunk 2 above)
Comment (rtBot) [inline languages/godam-hi_IN.l10n.php:1]: :no_entry_sign: **Error**: Filenames should be all lowercase with hyphens as word separators. Expected vipgoci-phpcs-scan-ckijz5.php, but found vipgoci-phpcs-scan-CkIJZ5.php (*WordPress.Files.FileName.NotHyphenatedLowercase*).

**Review by rtBot — DISMISSED** [review]
# Code analysis identified issues
[action-phpcs-code-review](https://github.com/rtCamp/action-phpcs-code-review/) has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


Powered by rtCamp's [GitHub Actions Library](https://github.com/rtCamp/github-actions-library)

**Comment by subodhr258** [comment]
Script Translations are set so that the translations are also visible on GoDAM pages:

https://github.com/user-attachments/assets/acf400c3-f6e2-4c10-a6ff-16b64abcae04

**Comment by mi5t4n** [comment]
> I have a few suggestions:
> 
> 1. Add a composer script to generate pot file and include `wp-cli/i18n-command` as composer dev dependency. Reference: https://github.com/rtCamp/login-with-google/blob/develop/composer.json
> 2. JS Strings are still not being translated
>    [Kazam_screencast_00003.webm](https://github.com/user-attachments/assets/cbefe434-7353-487e-be49-7b51562823a1)

@subodhr258 Could you address point 1 as well then we are good to go.

**Comment by subodhr258** [comment]
@mi5t4n I have updated the make-pot command in the composer.json file and tested it successfully:
```bash
subodhrajpopat@Subodhs-MacBook-Air godam % composer run pot
> WP_CLI_PHP_ARGS='-d memory_limit=1024M' ./vendor/bin/wp i18n make-pot . --exclude="assets/src,assets/node_modules,tests,vendor" ./languages/godam.pot
Plugin file detected.
Success: POT file successfully generated.
```
I had to modify the command because of `memory size of x bytes exhausted` issue.

However, there still seems to be a problem in some pages for translation. we tested the pages and it seems like the strings are not being translated in the Video Editor page and Media Library. We checked in the .pot, .po and .json files, the video-editor.js and media-library.js files are mentioned along with the translation, but it is not visible.
This console log isn't giving the translated output either for them:
```js
console.log( wp.i18n.__('Uncategorized', 'godam') );
Output: Uncategorized
```
We have checked that the `wp_set_script_translations()` function is correctly used before those scripts (the handles are `transcoder-page-script-video-editor` and `media-library-react` ) are enqueued.

**Review by KMchaudhary — APPROVED** [review]
