### PR TITLE
Fix the negative margin issue, and refactor the godam admin page UI

### LINKED ISSUE #886: Fix UI Alignment when GoDAM is used with debugger
There are UI Alignment issue when GoDAM Plugin is used with Debugger activated. [There seems to be negative margins]

Steps :

- Turn on debugger
- Observe responsiveness and UX experience in GoDAM Plugin

Image

### PR DESCRIPTION
**Pull request by KMchaudhary**
- Fix the GoDAM admin pages UI and negative margin.
- Fix the single video analytics heatmap layout break.
- Fix the GoDAM theme colors issue.
- Remove redudant CSS.

## **Before**
Screenshot 2025-08-12 at 12 16 32 PM

Screenshot 2025-08-12 at 12 17 18 PM

Screenshot 2025-08-12 at 12 17 48 PM

Screenshot 2025-08-12 at 12 18 34 PM

Screenshot 2025-08-12 at 12 19 05 PM

## **After**
Screenshot 2025-08-12 at 12 20 58 PM

Screenshot 2025-08-12 at 12 21 05 PM

Screenshot 2025-08-12 at 12 21 12 PM

Screenshot 2025-08-12 at 12 20 40 PM

### Closes
#886 #885

### CODE REVIEW

**Comment by prachigarg19** [comment]
### Additional point:
Could you also define a max-width for the single analytics container like we have in dashboard so all the content is inline?

**Issue trying to resolve:**
image

**How max-width in Dashboard looks**
image

**Comment by subodhr258** [comment]
@KMchaudhary Yeah, alignment with the header could be better though

File: inc/classes/class-pages.php [hunk 1]
```diff
@@ -320,6 +326,7 @@ public function render_godam_page() {
 	 */
 	public function render_video_editor_page() {
 		?>
+		<div class="godam-admin-root">
 		<div id="root-video-editor">
```
Comment (Juzar10) [inline inc/classes/class-pages.php:330]: Check indentation here.

File: pages/help/index.scss [hunk 2]
```diff
@@ -3,8 +3,8 @@
 }
 
 #wpbody-content {
-	background-image: url(../../assets/src/images/hero-bg.webp);
-	background-size: cover;
+	// background-image: url(../../assets/src/images/hero-bg.webp);
```
Comment (Juzar10) [inline pages/help/index.scss:6]: Check if this commented-out code needs to remain.

**Review by Juzar10 — APPROVED** [review]

**Review by prachigarg19 — APPROVED** [review]
